first PR
boris-catsvill/project-structure pull request #66
Opened 2022-10-17 00:43 UTC by k1ntsugi1

2022-10-23 16:38 UTC, dosandk commented on src/components/CategoriesList.js
> +    const categoryBody = `
может стоит вынести в отдельный шаблон?

2022-10-23 16:38 UTC, dosandk commented on src/components/CategoriesList.js
> +    const subCatListContainer = categoryElement.querySelector('[data-element="subCatListContainer"]');
может стоит вынести в отдельный метод?

2022-10-23 16:41 UTC, dosandk commented on src/components/CategoriesList.js
> +    const response = await fetch(this.url.toString());
а обработка ошибок где?
вдруг прийдет `response.ok = false`?

2022-10-23 16:42 UTC, dosandk commented on src/components/CategoriesList.js
> +    await this.setData();
а где подход "skeleton"?
почему мы не отобразить скелет страницы сначала, а потом наполнить его данными, полученными асинхронно?

2022-10-23 16:43 UTC, dosandk commented on src/components/ColumnChart.js
> +      url = ``,
а почему тут обратные кавычки?
а в строке 11 - обычные?

2022-10-23 16:44 UTC, dosandk commented on src/components/ColumnChart.js
> +        const JSONData = await response.json();
не самое удачное имя...
с заглавной буквы именуются только классы и ф-ции конструкторы

2022-10-23 16:45 UTC, dosandk commented on src/components/ColumnChart.js
> +import errorHandler from "../store/errorHandler";
а почему обработка ошибок находится в отдельном файле?
почему не используется `fetchJson`?
почему используется `fetch` напрямую?

2022-10-23 16:45 UTC, dosandk commented on src/components/DoubleSlider.js
> +export default class DoubleSlider {
👍 good

2022-10-23 16:45 UTC, dosandk commented on src/components/DoubleSlider.js
> +    for (let element of elements) {
`const element`

2022-10-23 16:46 UTC, dosandk commented on src/components/DoubleSlider.js
> +      const name = element.dataset.element.match(/(left|right|progress|to|from)/)[0];
зачем тут `match` и ругулярка?

2022-10-23 16:47 UTC, dosandk commented on src/components/DoubleSlider.js
> +    this.element.removeEventListener('pointerdown', this.pointerDownHandler);
это лишнее, снимать данный обработчик нет необходимости

2022-10-23 16:48 UTC, dosandk commented on src/components/Notification.js
> +      this.constructor.globalNotifictionElement?.remove();
🔴 please don't do this
так делать не следует: `this.constructor.globalNotifictionElement`
обращайтесь через `NotificationMessage.globalNotifictionElement`

2022-10-23 16:58 UTC, dosandk commented on src/components/Notification.js
> +      this.constructor.globalNotifictionElement?.remove();
```js
class NotificationMessage {
  static getName() {
    return "My name is NotificationMessage";
  }

  lognameA() {
    console.log(NotificationMessage.getName());
  }

  lognameB() {
    console.log(this.constructor.getName());
  }
}

class ErrorNotification extends NotificationMessage {
  static getName() {
    return "My name is ErrorNotification";
  }
}

const errorNotification = new ErrorNotification();

errorNotification.lognameA(); // My name is NotificationMessage
errorNotification.lognameB(); // My name is ErrorNotification
```

2022-10-23 16:59 UTC, dosandk commented on src/components/ProductForm.js
> +const IMGUR_CLIENT_ID = '28aaa2e823b03b1';
здесь следует использовать переменные окружения:
```
process.env
```

2022-10-23 17:01 UTC, dosandk commented on src/components/ProductForm.js
> +      return `<option value="${escapeHtml(id)}">${text}</option>`;
обратите внимание на `new Option`

2022-10-23 17:33 UTC, dosandk commented on src/components/ProductForm.js
> +    const { categories = [] } = this.data;
good 👍

2022-10-23 17:33 UTC, dosandk commented on src/components/ProductForm.js
> +    try {
good 👍

2022-10-23 17:34 UTC, dosandk commented on src/components/ProductForm.js
> +      const response = await fetch(product.toString(), {
а почему бы не воспользоваться ф-цией `fetchJson`

2022-10-23 17:35 UTC, dosandk commented on src/components/ProductForm.js
> +        const elementA = document.createElement('a');
что такое `elementA`?

2022-10-23 17:35 UTC, dosandk commented on src/components/ProductForm.js
> +      //throw new Error("Ошибка сети/Ошибка на сервере");
почему код закоменчен?

2022-10-23 17:36 UTC, dosandk commented on src/components/Sidebar.js
> +export default class Sidebar {
👍 good 
лайк за отделение в отдельный компонент сайдбара

2022-10-23 17:37 UTC, dosandk commented on src/components/Sidebar.js
> +  setActiveNavItemHandler = (href) => {
👍 good

2022-10-23 17:37 UTC, dosandk commented on src/components/SortableList.js
> +    this.items = SortableList.addClassesOfItems(items);
👍 good

2022-10-23 17:38 UTC, dosandk commented on src/components/SortableList.js
> +        endPositions: Array.from(this.element.children),
почему не `[...this.elements.children]`?

2022-10-23 17:39 UTC, dosandk commented on src/components/SortableTable.js
> +  scrollHandler = () => {
good 👍

2022-10-23 17:39 UTC, dosandk commented on src/components/SortableTable.js
> +      this.getDataFromServer().then(data => {
старайтесь использовать `await` везде где это возможно

2022-10-23 17:40 UTC, dosandk commented on src/components/SortableTable.js
> +    if (this.showingPage !== 'DashboardPage') {
🔴 please don't do this
так делать категорически нельзя!
компонент ничего не должен знать про какие-то 'DashboardPage'

2022-10-23 17:40 UTC, dosandk commented on src/components/SortableTable.js
> +    document.removeEventListener('scroll', this.scrollHandler);
👍 good

2022-10-23 17:41 UTC, dosandk commented on src/components/SortableTable.js
> +    const response = await fetch(this.url.toString());
а где обработка ошибки?

2022-10-23 17:41 UTC, dosandk commented on src/components/Tooltip.js
> +
а где объявление `static instance`?

2022-10-23 17:42 UTC, dosandk commented on src/components/Tooltip.js
> +    this.element.style.left = clientX + 10 + 'px';
10 и 15 следует вынести в переменными с соответствующими именами

2022-10-23 17:42 UTC, dosandk commented on src/components/Tooltip.js
> +  removeEventListeners() {
👍 good

2022-10-23 17:43 UTC, dosandk commented on src/main.js
> +const BACKEND_URL = 'https://course-js.javascript.ru/';
значение следует взять из переменных окружения

2022-10-23 17:48 UTC, dosandk commented on src/main.js
> +export default class Page {
тут происходит что-то странное...
`main.js` должен проинициализировать роутер, не вижу роутера...
А вот роутер уже примет решение какую страницу следует показывать

2022-10-23 17:49 UTC, dosandk commented on src/pages/CategoriesPage.js
> +  constructor({mainClass, url}) {
во все страницы параметр `url` приходить не должен,
в этом нет необходимости

2022-10-23 17:50 UTC, dosandk commented on src/pages/CategoriesPage.js
> +    const [[categoriesPath, subcategoriesPath], backendURL] = url;
если очень хочется загружать данные для всех компонент на страницы и удалить эту логику загрузки непосредственно из компонент, то `url` для запросов нужно хранить в этой странице а не в `main.js`

2022-10-23 17:50 UTC, dosandk commented on src/pages/CategoriesPage.js
> +    try {
👍 good

2022-10-23 17:52 UTC, dosandk commented on src/pages/DashBoardPage.js
> +  static containersForFillig = ['rangePicker', 'orders-chart', 'sales-chart', 'customers-chart', 'sortableTable'];
а почему поле статическое?

2022-10-23 17:53 UTC, dosandk commented on src/pages/DashBoardPage.js
> +  getHTMLDataOfElements() {
что происходит в данном методе?

2022-10-23 17:53 UTC, dosandk commented on src/pages/DashBoardPage.js
> +      if (nameOfConstructor === 'chart') {
почему здесь проверка опирается на строку `chart`?

2022-10-23 17:54 UTC, dosandk commented on src/pages/DashBoardPage.js
> +        data.url = (new URL(this.path + typeOfChart, this.backendURL)).toString();
почему имена контейнеров не получить из шаблона?

2022-10-23 17:54 UTC, dosandk commented on src/pages/ProductFormPage.js
> +    constructor({mainClass, productId, urls}) {
по `url` аналогичное замечание

2022-10-23 17:54 UTC, dosandk commented on src/pages/ProductFormPage.js
> +      this.urlsForAJAX = {
👍 good

2022-10-23 17:55 UTC, dosandk commented on src/pages/ProductFormPage.js
> +      this.wrapperOfElementHTML = new this.Constructor(this.productId, this.urlsForAJAX);
что такое `this.Constructor`?
почему такое странное имя свойства?

2022-10-23 17:56 UTC, dosandk commented on src/pages/UndefinedPage.js
> +    get undefinedElement() {
если страница уже называется `UndefinedPage`, почему метод тоже имеет в названии слово `undefined`? Ведь уже ясно что это `undefined` страница

2022-10-23 17:57 UTC, dosandk commented on src/pages/UndefinedPage.js
> +      const bodyOfUndefinedElement = `<a href="/">Страница не найдена. Перейти на главную</a>`;
зачем нужна эта промежуточная переменная?

2022-10-23 17:59 UTC, dosandk commented on webpack.config.js
> +if (process.env.NODE_ENV === 'production') {
может лучше тернарное выражение?

2022-10-23 17:59 UTC, dosandk commented on webpack.config.js
> +        exclude: /(node_modules|bower_components)/,
откуда и зачем тут `bower_components`?

2022-10-23 17:59 UTC, dosandk commented on webpack.config.js
> +module.exports = {
@k1ntsugi1 откуда эта конфигурация Webpack?

2022-10-23 18:00 UTC, dosandk requested changes
@k1ntsugi1 посмотрите комменты,
дайте ответы на вопросы!

2022-10-23 18:00 UTC, dosandk commented
@k1ntsugi1 куда делся роутер в приложении?

2022-10-26 10:52 UTC, k1ntsugi1 commented on webpack.config.js
> +module.exports = {
эта конфигурация вебпака с одного из моих пет-проектов, сейчас исправлю все замечания и отвечу на вопросы, что выше

2022-10-26 19:59 UTC, k1ntsugi1 commented on src/components/ColumnChart.js
> +      url = ``,
невнимательность, исправил

2022-10-26 19:59 UTC, k1ntsugi1 commented on src/components/ColumnChart.js
> +        const JSONData = await response.json();
невнимательность, исправил

2022-10-26 20:01 UTC, k1ntsugi1 commented on src/components/ColumnChart.js
> +import errorHandler from "../store/errorHandler";
хочется максимально самостоятельно реализовать проект, поэтому не использую ваш fetchJson.
Сделаю свой fetchJson.

2022-10-26 20:01 UTC, k1ntsugi1 commented on src/components/DoubleSlider.js
> +    for (let element of elements) {
исправил

2022-10-26 20:02 UTC, k1ntsugi1 commented on src/components/DoubleSlider.js
> +      const name = element.dataset.element.match(/(left|right|progress|to|from)/)[0];
Я тогда изучал их, поэтому хотелось использовать регулярку ), хотя смысла в этом нет в данном случае. Исправлю

2022-10-26 20:03 UTC, k1ntsugi1 commented on src/components/DoubleSlider.js
> +    this.element.removeEventListener('pointerdown', this.pointerDownHandler);
да, тогда еще не знал что при удалении элемента, его слушатели и слушатели его дочерних элементов удаляются, исправил

2022-10-26 20:04 UTC, k1ntsugi1 commented on src/components/Notification.js
> +      this.constructor.globalNotifictionElement?.remove();
исправил

2022-10-26 20:07 UTC, k1ntsugi1 commented on src/components/SortableTable.js
> +    const response = await fetch(this.url.toString());
добавлю в четверг-пятницу, когда буду делать кастомный fetch

2022-10-26 20:08 UTC, k1ntsugi1 commented on src/components/Tooltip.js
> +
исправил

2022-10-26 20:09 UTC, k1ntsugi1 commented on src/components/Tooltip.js
> +    this.element.style.left = clientX + 10 + 'px';
исправил

2022-10-26 20:09 UTC, k1ntsugi1 commented on src/main.js
> +const BACKEND_URL = 'https://course-js.javascript.ru/';
исправил

2022-10-26 20:09 UTC, k1ntsugi1 commented on src/main.js
> +export default class Page {
исправил, сделал свой роутер на основе вашего

2022-10-26 20:11 UTC, k1ntsugi1 commented on src/pages/DashBoardPage.js
> +  static containersForFillig = ['rangePicker', 'orders-chart', 'sales-chart', 'customers-chart', 'sortableTable'];
тогда делал "в лоб", сейчас занимаюсь рефакторингом, исправлено путем вынесения в отельный файл компонентов которые нужно отрисовать

2022-10-26 20:14 UTC, k1ntsugi1 commented on src/pages/DashBoardPage.js
> +  getHTMLDataOfElements() {
он нужен был для создания нужных компонентов и инициализации контейнеров, где эти компоненты отрисовывались бы,  исправлено путем вынесения в отельный файл компонентов, которые нужно отрисовать с необходимыми для этого данными

2022-10-26 20:15 UTC, k1ntsugi1 commented on src/pages/DashBoardPage.js
> +      if (nameOfConstructor === 'chart') {
нужно было отрисовывать три комопнента с немного разными данными, поэтому ввел эту проверку, исправлено путем вынесения в отельный файл компонентов, которые нужно отрисовать с необходимыми для этого данными

2022-10-26 20:15 UTC, k1ntsugi1 commented on src/pages/DashBoardPage.js
> +        data.url = (new URL(this.path + typeOfChart, this.backendURL)).toString();
исправлено

2022-10-26 20:15 UTC, k1ntsugi1 commented on src/pages/UndefinedPage.js
> +    get undefinedElement() {
исправлено

2022-10-26 20:16 UTC, k1ntsugi1 commented on webpack.config.js
> +        exclude: /(node_modules|bower_components)/,
мой старый конфиг был использован, исправлено

2022-10-26 20:17 UTC, k1ntsugi1 commented
> @k1ntsugi1 куда делся роутер в приложении?

Так как я делал сборку вперед занятий, то самостоятельно реализовывал роутинг и вебпак. Исправлено путем создания своего роутера на основе вашего

2022-10-26 20:19 UTC, k1ntsugi1 commented on src/components/SortableTable.js
> +    if (this.showingPage !== 'DashboardPage') {
а если на разных страницах используется один и тот же компонент, но сервер требует, в зависимости от страницы, разные параметры queryString?

2022-10-26 21:59 UTC, k1ntsugi1 commented on src/components/CategoriesList.js
> +    await this.setData();
исправлено

2022-10-26 22:00 UTC, k1ntsugi1 commented on src/components/ProductForm.js
> +const IMGUR_CLIENT_ID = '28aaa2e823b03b1';
исправлено

2022-10-26 22:23 UTC, k1ntsugi1 commented on src/components/ProductForm.js
> +      return `<option value="${escapeHtml(id)}">${text}</option>`;
исправлено

2022-10-26 22:24 UTC, k1ntsugi1 commented on src/components/ProductForm.js
> +        const elementA = document.createElement('a');
переименовал

2022-10-26 22:24 UTC, k1ntsugi1 commented on src/components/ProductForm.js
> +      //throw new Error("Ошибка сети/Ошибка на сервере");
обработку ошибок буду делать, когда буду делать кастомный fetchJSON

2022-10-26 22:25 UTC, k1ntsugi1 commented on src/components/SortableList.js
> +        endPositions: Array.from(this.element.children),
невнимательность, исправлено

2022-10-26 22:27 UTC, k1ntsugi1 commented on src/pages/ProductFormPage.js
> +      this.wrapperOfElementHTML = new this.Constructor(this.productId, this.urlsForAJAX);
подумал, что введение поля this.Constructor будет удобно в будущем, если захочу изменить на другой компонент формы, исправлено

2022-10-26 22:29 UTC, k1ntsugi1 commented on src/pages/UndefinedPage.js
> +      const bodyOfUndefinedElement = `<a href="/">Страница не найдена. Перейти на главную</a>`;
не совсем понял вопрос

2022-10-26 22:30 UTC, k1ntsugi1 commented on src/pages/CategoriesPage.js
> +    const [[categoriesPath, subcategoriesPath], backendURL] = url;
понял, исправил

2022-10-26 22:33 UTC, k1ntsugi1 commented
> _ No description provided. _

2022-10-27 10:12 UTC, k1ntsugi1 commented on src/components/SortableTable.js
> +    if (this.showingPage !== 'DashboardPage') {
UPD: исправил

2022-10-27 10:13 UTC, k1ntsugi1 commented on src/pages/ProductFormPage.js
> +    constructor({mainClass, productId, urls}) {
исправил

2022-10-27 18:20 UTC, k1ntsugi1 commented on src/components/ColumnChart.js
> +import errorHandler from "../store/errorHandler";
UPD: по итогу решил использовать ваш fetchJson, обработчик ошибок вынес в главный компонент - App

2022-10-27 18:20 UTC, k1ntsugi1 commented on src/components/ProductForm.js
> +      const response = await fetch(product.toString(), {
исправлено

2022-10-27 18:27 UTC, k1ntsugi1 commented on src/components/CategoriesList.js
> +    const categoryBody = `
исправлено

2022-10-27 18:27 UTC, k1ntsugi1 commented on src/components/CategoriesList.js
> +    const subCatListContainer = categoryElement.querySelector('[data-element="subCatListContainer"]');
исправлено

2022-11-01 13:49 UTC, dosandk commented on src/components/CategoriesList.js
> +    const response = await fetch(this.url.toString());
good 👍

2022-11-01 13:50 UTC, dosandk commented on src/components/ColumnChart.js
> +import errorHandler from "../store/errorHandler";
good 👍

2022-11-01 13:50 UTC, dosandk commented on src/components/DoubleSlider.js
> +    for (let element of elements) {
good 👍

2022-11-01 13:50 UTC, dosandk commented on src/components/DoubleSlider.js
> +      const name = element.dataset.element.match(/(left|right|progress|to|from)/)[0];
ок-ок

2022-11-01 13:50 UTC, dosandk commented on src/components/DoubleSlider.js
> +    this.element.removeEventListener('pointerdown', this.pointerDownHandler);
👍 good

2022-11-01 13:56 UTC, dosandk commented on .env
> +BESTSELLERS_DASHBOARD_URL=/api/dashboard/bestsellers
в чем смысл данного файла ".env"?
смысл в том что тут описываются значения к-е зависят от окружения 
или проще говоря сервера, но к-й мы заливаем наше приложение.

Вот например для конечного пользователя мы будем отправлять наш собранный проект на сервер, к-й назовем "production". Так вот для этого сервера наш BACKEND_URL = https://course-js.javascript.ru
А вот для локальной разработки наш BACKEND_URL может иметь значение BACKEND_URL = http://localhost:9001 

А вот ORDERS_DASHBOARD_URL или CUSTOMERS_DASHBOARD_URL будут идентичны для всех серверов/окружений:
http://localhost:9001/api/dashboard/orders
или
https://course-js.javascript.ru/api/dashboard/orders

Поэтому все ссылки должны жить в обычном `config.js` файле

2022-11-01 13:56 UTC, dosandk commented on src/App.js
> +	static instance = null
нет необходимости инициализировать значение с помощью `null`

2022-11-01 13:57 UTC, dosandk commented on src/App.js
> +		if (App.instance) { return App.instance; }
good 👍

2022-11-01 13:57 UTC, dosandk commented on src/App.js
> +		} catch (error) {
good 👍

2022-11-01 13:57 UTC, dosandk commented on src/App.js
> +		this.router
good 👍

2022-11-01 13:58 UTC, dosandk commented on src/components/SortableTable.js
> +    const typeOfContainer = this.clickableRows ? 'a' : 'div';
good 👍

2022-11-01 13:59 UTC, dosandk commented on src/pages/CategoriesPage/CategoriesPage.js
> +      //errorHandler(error);
не оставляйте закомментированный код

2022-11-01 14:01 UTC, dosandk approved these changes
👍 good 
отлично что проделали огромную работу над ошибками!
very good
работа принята, поздравляю

2022-11-01 14:53 UTC, k1ntsugi1 commented
Спасибо еще раз за курс, было интересно и полезно!

2023-01-19 13:39 UTC, closed without merging